# Generated by Django 3.2.4 on 2021-06-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='date')),
                ('members', models.IntegerField(max_length=10)),
                ('district', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('restaurant', models.CharField(max_length=100)),
                ('food_type', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
